//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildCustomPolicy.LocalAccounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PolicyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildCustomPolicy.LocalAccounts.PolicyResources", typeof(PolicyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;TrustFrameworkPolicy
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/online/cpim/schemas/2013/06&quot;
        ///  PolicySchemaVersion=&quot;0.3.0.0&quot;
        ///  TenantId=&quot;{{yourtenant}}.onmicrosoft.com&quot;
        ///  PolicyId=&quot;B2C_1A_PasswordReset&quot;
        ///  PublicPolicyUri=&quot;http://{{yourtenant}}.onmicrosoft.com/B2C_1A_PasswordReset&quot;&gt;
        ///
        ///  &lt;BasePolicy&gt;
        ///    &lt;TenantId&gt;{{yourtenant}}.onmicrosoft.com&lt;/T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;TrustFrameworkPolicy
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/online/cpim/schemas/2013/06&quot;
        ///  PolicySchemaVersion=&quot;0.3.0.0&quot;
        ///  TenantId=&quot;{{yourtenant}}.onmicrosoft.com&quot;
        ///  PolicyId=&quot;B2C_1A_ProfileEdit&quot;
        ///  PublicPolicyUri=&quot;http://{{yourtenant}}.onmicrosoft.com/B2C_1A_ProfileEdit&quot;&gt;
        ///
        ///  &lt;BasePolicy&gt;
        ///    &lt;TenantId&gt;{{yourtenant}}.onmicrosoft.com&lt;/Tenan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;TrustFrameworkPolicy
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/online/cpim/schemas/2013/06&quot;
        ///  PolicySchemaVersion=&quot;0.3.0.0&quot;
        ///  TenantId=&quot;{{yourtenant}}.onmicrosoft.com&quot;
        ///  PolicyId=&quot;B2C_1A_SignUp_SignIn&quot;
        ///  PublicPolicyUri=&quot;http://{{yourtenant}}.onmicrosoft.com/B2C_1A_signup_signin&quot;&gt;
        ///
        ///  &lt;BasePolicy&gt;
        ///    &lt;TenantId&gt;{{yourtenant}}.onmicrosoft.com&lt;/T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SignUpOrSignin {
            get {
                return ResourceManager.GetString("SignUpOrSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;TrustFrameworkPolicy
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns=&quot;http://schemas.microsoft.com/online/cpim/schemas/2013/06&quot;
        ///  PolicySchemaVersion=&quot;0.3.0.0&quot;
        ///  TenantId=&quot;{{yourtenant}}.onmicrosoft.com&quot;
        ///  PolicyId=&quot;B2C_1A_TrustFrameworkBase&quot;
        ///  PublicPolicyUri=&quot;http://{{yourtenant}}.onmicrosoft.com/B2C_1A_TrustFrameworkBase&quot;&gt;
        ///
        ///  &lt;BuildingBlocks&gt;
        ///    &lt;ClaimsSchema&gt;
        ///      &lt;!-- Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrustFrameworkBase {
            get {
                return ResourceManager.GetString("TrustFrameworkBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TrustFrameworkPolicy 
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///  xmlns=&quot;http://schemas.microsoft.com/online/cpim/schemas/2013/06&quot; 
        ///  PolicySchemaVersion=&quot;0.3.0.0&quot; 
        ///  TenantId=&quot;{{yourtenant}}.onmicrosoft.com&quot; 
        ///  PolicyId=&quot;B2C_1A_TrustFrameworkCommonExtensions&quot; 
        ///  PublicPolicyUri=&quot;http://{{yourtenant}}.onmicrosoft.com/B2C_1A_TrustFrameworkExtensions&quot;&gt;
        ///  
        ///  &lt;BasePolicy&gt;
        ///    &lt;TenantId&gt;{{yourtenant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrustFrameworkExtensions_Common {
            get {
                return ResourceManager.GetString("TrustFrameworkExtensions_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TrustFrameworkPolicy 
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///  xmlns=&quot;http://schemas.microsoft.com/online/cpim/schemas/2013/06&quot; 
        ///  PolicySchemaVersion=&quot;0.3.0.0&quot; 
        ///  TenantId=&quot;{{yourtenant}}.onmicrosoft.com&quot; 
        ///  PolicyId=&quot;B2C_1A_TrustFrameworkEnvironmentExtensions&quot; 
        ///  PublicPolicyUri=&quot;http://{{yourtenant}}.onmicrosoft.com/B2C_1A_TrustFrameworkExtensions&quot;&gt;
        ///  
        ///  &lt;BasePolicy&gt;
        ///    &lt;TenantId&gt;{{yourt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrustFrameworkExtensions_Env {
            get {
                return ResourceManager.GetString("TrustFrameworkExtensions_Env", resourceCulture);
            }
        }
    }
}
